# Generated by Django 3.1.2 on 2020-12-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='images/', width_field=100),
        ),
    ]
